name:                dnd-assistant
version:             0.1.0.0
github:              "githubuser/dnd-assistant"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dnd-assistant#readme>

ghc-options:
  - -Wall
  - -fwarn-tabs

dependencies:
- base >= 4.7 && < 5
- readline
- containers
- random
- split
- directory
- mtl

library:
  source-dirs: src

executables:
  dnd-assistant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dnd-assistant

tests:
  dnd-assistant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dnd-assistant
